import { Lines, NewWine } from "@/interfaces";
import { v4 as uuid } from 'uuid';

export const newWineData: NewWine[] = [
  {
    id: uuid(),
    name: "PET NAT",
    image: "",
    description: "método de elaboración que nació por accidente en Francia en el Siglo XVI. Este método ancestral resulta en  un vino espumoso a través de una sola fermentación, a diferencia del método tradicional o Champenoise en el que se producen dos fermentaciones. 'Se caracteriza por tener un  proceso de elaboración sin agregados, solo acompañando por la transformación de azúcar en alcohol de manera paulatina.Como termina su fermentación en la misma botella que luego se comercializa, no es  filtrado, por lo que presenta una ¨neblina¨ que es parte de su expresión natural y bien característica de este método'",
    origin: "CAFAYATE - SALTA - ARGENTINA",
    elaboration: "Pet Nat o Pétillant Naturel",
    alcohol: "11 %",
    conservation: "8 MESES EN BOTELLA",
    harvestDate: "PRIMER QUINCENA DE FEBRERO. COSECHADO A MANO, EN CAJAS DE 15 KG. PRESELECCIÓN EN VIÑEDO",
    pairing: "Ideal para acompañar las tardes veraniegas y calurosas, antes de alguna comida, como refresco",
    suggar: "3 g/lt",
    temperature: "Temperatura de servicio de este vino es entre 4º y 6º C",
    variety: "TORRONTÉS 100%",
    vineyardAge: "30 AÑOS",
    vineyardHeight: "1.800 METROS SOBRE EL NIVEL DEL MAR. RUTA 40 KM 4347,4",
    line: Lines.espumantes
  },
  {
    id: uuid(),
    name: "Torrontés Brut Nature",
    image: "",
    description: "Espléndido espumante único en el Valle, presenta excelente calidad y persistencia en sus Burbujas. Sus aromas recuerdan rosas, durazno blanco y manzana verde, característicos del Torrontés, con notas de pan fresco y levadura producidos por la fermentación en botella. En boca resulta de gran estructura y agradable sensación fresca, que invita a seguir tomándolo.",
    origin: "CAFAYATE - SALTA - ARGENTINA",
    elaboration: "Maceración de la fruta y fermentaciones a bajas temperaturas para lograr aromas únicos, burbujas finas y persistentes. Segunda fermentación dentro de cada botella. Toma de espuma y degüelle realizados en forma artesanal buscando delicadeza en el producto. Agregado de licor de Expedición elaborado por nosotros para darle un matiz dulzón, propio de los Extra Brut.",
    alcohol: "12° C.",
    conservation: "",
    harvestDate: "Principios de Enero, bien temprano y a mano, cajas de 15 Kg.",
    pairing: "",
    suggar: "11G/L.",
    temperature: "",
    variety: "Torrontés 100%.",
    vineyardAge: "",
    vineyardHeight: "1.800 mts. sobre el nivel del mar.",
    line: Lines.espumantes
  },
  {
    id: uuid(),
    name: "Torrontés Extra Brut",
    image: "",
    description: "Este espumante Torrontés emblemático de Cafayate, destaca por su frescura y facilidad para tomar, tiene notas a pan fresco, maracuyá y durazno. Burbujas delicadas y pequeñas producidas por la segunda fermentación en botella. Gran estructura en boca, envolvente y persistente",
    origin: "CAFAYATE - SALTA - ARGENTINA",
    elaboration: "Maceración de la fruta y fermentaciones a bajas temperaturas para lograr aromas únicos, burbujas finas y persistentes. Segunda fermentación dentro de cada botella. Toma de espuma y degüelle realizados en forma artesanal buscando delicadeza en el producto. Agregado de licor de Expedición elaborado por nosotros para darle un matiz dulzón propio de los Extra Brut.",
    alcohol: "12 %",
    conservation: "En un lugar oscuro y sin vibraciones.",
    harvestDate: "Principios de enero bien temprano y a mano, cajas de 15 KG.",
    pairing: "Ensaladas frescas, pastas con crema, empanadas",
    suggar: "11 G/L.",
    temperature: "Entre 2° y 6°C.",
    variety: "100% Torrontes",
    vineyardAge: "",
    timeOnLees:"18 meses",
    vineyardHeight: "1.800 metros sobre el nivel del mar.",
    line: Lines.espumantes
  },
  {
    id: uuid(),
    name: "Rosé Malbec",
    image: "",
    description: "Espumante que destaca la uva emblemática de Argentina, con un color seductor y aromas a frutos rojos que se convierten luego en mermeladas, y frutos secos, producto de su re-fermentación en botella. Agradable matices frescos y maduros, con excelente calidad y persistencia en sus Burbujas, que lo hace aun mas fácil de tomar.",
    origin: "CAFAYATE - SALTA - ARGENTINA",
    elaboration: "Trabajando a bajas temperaturas desde el ingreso de la uva a bodega para obtener un color atractivo en la prensada y, junto a fermentaciones controladas, logramos aromas únicos, burbujas finas y persistentes. Toma de espuma realizada en forma artesanal y dedicada a la delicadeza del producto. Segunda fermentación dentro de cada botella.",
    alcohol: "13,5ºC",
    conservation: "12 meses",
    harvestDate: "Principios de Febrero.",
    pairing: "Risotto de hongos, canbutia rellena, sushi, pastas rellenas",
    suggar: "5 g/l",
    temperature: "",
    variety: "Malbec 100 %.",
    vineyardAge: "27 años",
    vineyardHeight: "1.800 mts. sobre el nivel del mar.",
    line: Lines.espumantes
  },
  {
    id: uuid(),
    name: "Chardonnay Nature",
    image: "",
    description: "Varietal reina de los espumantes, sus aromas hacen recordar elegantes notas a perfumes frutales, miel y pan tostado. En boca resulta sabores poderosos y cercano a ananá (o piña). Con un cuerpo ligero, con acidez pronunciada y buen equilibrio, que invita a seguir bebiéndolo",
    origin: "",
    elaboration: "",
    alcohol: "",
    conservation: "",
    harvestDate: "",
    pairing: "",
    suggar: "",
    temperature: "",
    variety: "",
    vineyardAge: "",
    vineyardHeight: "",
    line: Lines.espumantes
  },
  {
    id: uuid(),
    name: "Torrontés",
    image: "",
    description: "Varietal Emblemático de Cafayate - Norte Argentino . Color límpido como el agua, genera sensación de frescura y fineza. Aroma cítricos y flores blancas envuelven el ambiente. Sutil cremosidad y mineralizada en boca, procovando un equilibrio único en el paladar.",
    origin: "CAFAYATE - SALTA - ARGENTINA",
    elaboration: "Maceración de la uva con frío antes de su prensado. Fermentación a bajas temperaturas para preservar frescura.",
    alcohol: "",
    conservation: "En lugar fresco, oscuro y sin vibraciones.",
    harvestDate: "Principio de Febrero, cosechado a mano en cajas de 15 Kg. Preselección en viñedo.",
    pairing: "Ideal para acompañar quesos fuertes, mariscos, sushi y también empanadas salteñas. Se recomienda con comidas en verano y como aperitivo en invierno.",
    suggar: "",
    temperature: "Entre 3° y 7° C.",
    variety: "Torrontés 100%.",
    vineyardAge: "25 años.",
    vineyardHeight: "1.800 mts. sobre el nivel del mar.",
    line: Lines.tinquiao
  },
  {
    id: uuid(),
    name: "Torrontés Dulce Natural",
    image: "",
    description: "De color amarillo verdoso atractivo y brillante, invita a la boca sus aromas cítricos preponderantes mezclados con una sensación tropical. Tiene una entrada dulce equilibrada con delicadas notas a limón, pomelo, durazno blanco. El dulce Natural de la uva genera una untuosidad interesante que al sentirlo recuerda a miel en panal, con un final presente por un largo tiempo.",
    origin: "CAFAYATE - SALTA - ARGENTINA",
    elaboration: "Maceración y fermentación con levaduras seleccionadas naturalmente de la uva. Fermentación lenta y con frío, hasta obtener el azúcar y alcohol deseados.",
    alcohol: "",
    conservation: "En lugar fresco, oscuro y sin vibraciones.",
    harvestDate: "Marzo. Cosecha bien temprano y a mano. Cajas de 15 Kg.",
    pairing: "Ideal para beber como aperitivo acompañando tabla de quesos y/o frutos secos. Tartas dulces con crema. También para preparar cocteles.",
    suggar: "",
    temperature: "",
    variety: "Torrontés 100%.",
    vineyardAge: "25 años.",
    vineyardHeight: "1.800 mts. sobre el nivel del mar.",
    line: Lines.tinquiao
  },
  {
    id: uuid(),
    name: "Rosé Malbec",
    image: "",
    description: "Predomina un rosado atractivo y brillante. En boca tiene una entrada agradable y de buen volumen, con una acidez vibrante y fresca que le da carácter. Entrelazan aromas de cereza, guinda, frutilla; final envolvente en boca que recuerda a mermelada recién realizada de frutos rojos.",
    origin: "",
    elaboration: "",
    alcohol: "",
    conservation: "",
    harvestDate: "",
    pairing: "",
    suggar: "",
    temperature: "",
    variety: "",
    vineyardAge: "",
    vineyardHeight: "",
    line: Lines.tinquiao
  },
  {
    id: uuid(),
    name: "Cabernet Sauvignon",
    image: "",
    description: "Color rubí y violáceo con detalles negruzcos. Aromas que recuerdan a frutos negros, especies mentoladas, pimiento verde. En boca y nariz se pueden encontrar los mismos aromas, dejando la sensación de continuar bebiéndolo. De acidez punzante y taninos suaves, que le otorga buen cuerpo y un final elegante y persistente.",
    origin: "",
    elaboration: "",
    alcohol: "",
    conservation: "",
    harvestDate: "",
    pairing: "",
    suggar: "",
    temperature: "",
    variety: "",
    vineyardAge: "",
    vineyardHeight: "",
    line: Lines.tinquiao
  },
  {
    id: uuid(),
    name: "Malbec",
    image: "",
    description: "Color púrpura con matices rojizos, oscuro en el centro. Aromas que recuerdan a frutos rojos, destacándose la ciruela y cereza sobre-madura. Es inicialmente suave, luego se torna complejo y estructurado, con un acabado persistente. Es un vino con mucha personalidad, debido a la altitud y las grandes amplitudes térmicas de los viñedos Cafayateños.",
    origin: "",
    elaboration: "",
    alcohol: "",
    conservation: "",
    harvestDate: "",
    pairing: "",
    suggar: "",
    temperature: "",
    variety: "",
    vineyardAge: "",
    vineyardHeight: "",
    line: Lines.tinquiao
  },
  {
    id: uuid(),
    name: "Blend",
    image: "",
    description: "Tri-varietal de color rojo oscuro con matices violáceos. Aromas que me transportan a frutos rojos maduros y especies de campo. En boca, los aromas expresados por cada varietal se entremezclan formando un bouquet fino y elegante.",
    origin: "",
    elaboration: "",
    alcohol: "",
    conservation: "",
    harvestDate: "",
    pairing: "",
    suggar: "",
    temperature: "",
    variety: "",
    vineyardAge: "",
    vineyardHeight: "",
    line: Lines.tinquiao
  },
  {
    id: uuid(),
    name: "",
    image: "",
    description: "",
    origin: "",
    elaboration: "",
    alcohol: "",
    conservation: "",
    harvestDate: "",
    pairing: "",
    suggar: "",
    temperature: "",
    variety: "",
    vineyardAge: "",
    vineyardHeight: "",
    line: Lines.espumantes
  },
]